### ISSUE TITLE
テーブルの主キーはvarchar型を使わない

### ISSUE THREAD

**Issue by yoshi-koyama** [nemoskii/CRUD-MyBatis#2]
# 概要
テーブルの主キーにvarcharを使うのは特段の事情がない限りは避けてほしいです。
https://github.com/nemoskii/CRUD-MyBatis/blob/master/src/main/resources/schema.sql
なぜ避けたほうがいいのか？についても調べてみてほしいです。

# 完了の定義
- [x] テーブル設計の見直しがされていること
- [x] VARCHAR型を避ける理由が明確になっていること

# 参考資料
日本語でもよいですが、英語でも検索してみるといいでしょう。
`sql primary key varchar`
`mysql primary key varchar`
など

**Comment by koma236** [comment]
すみません、完了の定義「VARCHAR型を避ける理由」を誤って削除してしまいました。

・一意性
・データサイズを小さくするのが原則
というのが大きな理由と理解しました。

[一意性]
→今回のprimary keyがメールアドレスだったため、将来的に変更の可能性がゼロではないため、不適当

[データサイズ]
→ int型は4bytes、varchar型はutf-8 １文字で1~4bytes使う。外部キーとして使われる場合のセカンダリインデックスのサイズも考慮する必要がある。

（他にも理由があった気がするのですが、テーブル設計を修正しているうちに失念してしまいました。）

よろしくお願いいたします。

**Comment by yoshi-koyama** [comment]
@nemoskii 

> すみません、完了の定義「VARCHAR型を避ける理由」を誤って削除してしまいました。

大丈夫です。戻しておきました。

ついでにチェックボックスを入力する方法を調べてみてください。
`github markdown checkbox`
とかで出ると思います。

記載されている理由について問題ないです！
チェックボックスにチェックを付けておきました。

理由として、他にはvarcharだとauto_incrementで自動で発行ができないとかですかね。
文字列をidに絶対に使わないということはないのですが基本はint型で大丈夫です！

Tips
あとはintにくわえてunsignedを利用して適応できる桁数を増やすということをする場合もあります。

**Comment by koma236** [comment]
テーブル設計の見直し修正、完了してマージしました。
